# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-11-14 09:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Leucocite(WBC)', 'Leucocite(WBC)'), ('Hematii(RBC)', 'Hematii(RBC)'), ('Hemoglobina(HGB)', 'Hemoglobina(HGB)'), ('VEM(volum eritocitar mediu)', 'VEM(volum eritocitar mediu'), ('HEM(hemoglobina eritocitara medie)', 'HEM(hemoglobina eritocitara medie)'), ('CHEM(conc HB eritocitara medie)', 'CHEM(conc HB eritocitara medie)'), ('RDW', 'RDW'), ('Trombocite(PLT)', 'Trombocite'), ('MPW', 'MPW'), ('PDW', 'PDW'), ('Neutro', 'Neutro'), ('Lym', 'Lym'), ('Monocite', 'Monocite'), ('Eozinofile', 'Eozinofile'), ('Bazofile', 'Bazofile'), ('Creatinina serica', 'Creatinina serica'), ('Magneziu seric', 'Magneziu seric'), ('Sideremie', 'Sideremie'), ('Glicemie', 'Glicemie'), ('TGP', 'TGP'), ('TSH', 'TSH'), ('FT4', 'FT4')], default='Leucocite(WBC)', max_length=100, verbose_name='Name')),
                ('abbr', models.CharField(blank=True, max_length=10, null=True, verbose_name='Abbreviation')),
                ('category', models.CharField(choices=[('Hematologie', 'Hematologie'), ('Biochimie', 'Biochimie'), ('Dozari hormonale, Imunologie si markeri tumorali (Chemiluminiscenta)', 'Dozari hormonale, Imunologie si markeri tumorali (Chemiluminiscenta)')], default='Hematologie', max_length=100, verbose_name='Category')),
                ('um', models.CharField(choices=[('10^3/mm3', '10^3/mm3'), ('10^6/mm3', '10^6/mm3'), ('g/dl', 'g/dl'), ('%', '%'), ('fL', 'fL'), ('mg/dl', 'mg/dl'), ('U\\L', 'U\\L'), ('μUI\\ml', 'μUI\\ml'), ('ng/dl', 'ng/dl')], default='10^3/mm3', max_length=10, verbose_name='Unit')),
            ],
        ),
        migrations.CreateModel(
            name='Lab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True, verbose_name='Date')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
        migrations.CreateModel(
            name='LabGeneral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('threshold_min', models.DecimalField(decimal_places=2, default=0, max_digits=4, null=True, verbose_name='Min Value')),
                ('threshold_max', models.DecimalField(decimal_places=2, default=0, max_digits=4, null=True, verbose_name='Max Value')),
                ('item_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ItemGeneral', to='healthy.Item')),
            ],
        ),
        migrations.CreateModel(
            name='LabResults',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=4, null=True, verbose_name='Value')),
                ('general_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='LabGeneral', to='healthy.LabGeneral')),
                ('item_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Item', to='healthy.Item', verbose_name='Marker')),
                ('lab_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Lab', to='healthy.Lab')),
                ('user_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('F', 'F'), ('M', 'M')], default='F', max_length=5)),
                ('dob', models.DateField(null=True, verbose_name='Date of birth')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True)),
            ],
        ),
    ]
