# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-11-14 12:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('healthy', '0002_labdetail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labdetail',
            name='user_ref',
        ),
    ]
