# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-11-14 13:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('healthy', '0003_remove_labdetail_user_ref'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labdetail',
            name='lab_ref',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='LabDet', to='healthy.Lab', unique=True),
        ),
    ]
