# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-11-29 12:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthy', '0005_auto_20161114_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='lab',
            name='collection_point',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Collection point'),
        ),
        migrations.AddField(
            model_name='lab',
            name='doctor',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Doctor'),
        ),
        migrations.AddField(
            model_name='lab',
            name='patient_code',
            field=models.IntegerField(null=True, verbose_name='Patient Code'),
        ),
        migrations.AddField(
            model_name='lab',
            name='ref_number',
            field=models.IntegerField(default=123, verbose_name='Reference Number'),
            preserve_default=False,
        ),
    ]
