# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-11-29 13:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('healthy', '0006_auto_20161129_1411'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labdetail',
            name='lab_ref',
        ),
        migrations.DeleteModel(
            name='LabDetail',
        ),
    ]
