# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-11-29 13:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthy', '0007_auto_20161129_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labgeneral',
            name='threshold_max',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=10, null=True, verbose_name='Max Value'),
        ),
        migrations.AlterField(
            model_name='labgeneral',
            name='threshold_min',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=10, null=True, verbose_name='Min Value'),
        ),
        migrations.AlterField(
            model_name='labresults',
            name='value',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=10, null=True, verbose_name='Value'),
        ),
    ]
